language: php

sudo: false

git:
  depth: 1

matrix:
    include:
        - php: 5.4
        - php: 5.5
        - php: 5.6
        - php: 7.0
        - php: hhvm
        - php: nightly
    allow_failures:
        - php: 7.0
        - php: hhvm
        - php: nightly
    fast_finish: true

script:
  - phpize
  - ./configure
  - make -j$(($(nproc)+1))
  - make test
